language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose -i https://pypi.tuna.tsinghua.edu.cn/simple

script:
  - docker-compose run app sh -c "python manage.py test && flake8"